# Generated by Django 4.2.7 on 2025-10-18 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Subir imagen en formato JPG, JPEG o PNG', upload_to='skin_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('predicted_class', models.CharField(blank=True, choices=[('akiec', 'Actinic keratoses (Queratosis actínicas)'), ('bcc', 'Basal cell carcinoma (Carcinoma basocelular)'), ('bkl', 'Benign keratosis (Queratosis benigna)'), ('df', 'Dermatofibroma'), ('mel', 'Melanoma'), ('nv', 'Melanocytic nevi (Nevos melanocíticos)'), ('vasc', 'Vascular lesions (Lesiones vasculares)')], max_length=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confianza de la predicción (0-1)', null=True)),
                ('probabilities', models.JSONField(blank=True, help_text='Probabilidades de todas las clases', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('image_size', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo en segundos', null=True)),
            ],
            options={
                'verbose_name': 'Predicción de Enfermedad Cutánea',
                'verbose_name_plural': 'Predicciones de Enfermedades Cutáneas',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
