# Generated by Django 5.2.7 on 2025-11-04 21:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Subir imagen en formato JPG, JPEG o PNG', upload_to='skin_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('predicted_class', models.CharField(blank=True, choices=[('akiec', 'Actinic keratoses (Queratosis actínicas)'), ('bcc', 'Basal cell carcinoma (Carcinoma basocelular)'), ('bkl', 'Benign keratosis (Queratosis benigna)'), ('df', 'Dermatofibroma'), ('mel', 'Melanoma'), ('nv', 'Melanocytic nevi (Nevos melanocíticos)'), ('vasc', 'Vascular lesions (Lesiones vasculares)')], help_text='Clase de enfermedad predicha por el modelo', max_length=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confianza de la predicción (0-1)', null=True)),
                ('probabilities', models.JSONField(blank=True, help_text='Probabilidades de todas las clases en formato JSON', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida de la imagen')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha y hora de procesamiento por la IA', null=True)),
                ('image_size', models.CharField(blank=True, help_text='Dimensiones de la imagen (ancho x alto)', max_length=50, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que creó la predicción (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predicción de Enfermedad Cutánea',
                'verbose_name_plural': 'Predicciones de Enfermedades Cutáneas',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='uploaded_at_idx'), models.Index(fields=['predicted_class'], name='predicted_class_idx')],
            },
        ),
    ]
