# Generated by Django 4.2.7 on 2025-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinimageprediction',
            name='image_size',
            field=models.CharField(blank=True, help_text='Dimensiones de la imagen (ancho x alto)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skinimageprediction',
            name='predicted_class',
            field=models.CharField(blank=True, choices=[('akiec', 'Actinic keratoses (Queratosis actínicas)'), ('bcc', 'Basal cell carcinoma (Carcinoma basocelular)'), ('bkl', 'Benign keratosis (Queratosis benigna)'), ('df', 'Dermatofibroma'), ('mel', 'Melanoma'), ('nv', 'Melanocytic nevi (Nevos melanocíticos)'), ('vasc', 'Vascular lesions (Lesiones vasculares)')], help_text='Clase de enfermedad predicha por el modelo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skinimageprediction',
            name='probabilities',
            field=models.JSONField(blank=True, help_text='Probabilidades de todas las clases en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='skinimageprediction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de procesamiento por la IA', null=True),
        ),
        migrations.AlterField(
            model_name='skinimageprediction',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='skinimageprediction',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida de la imagen'),
        ),
        migrations.AddIndex(
            model_name='skinimageprediction',
            index=models.Index(fields=['-uploaded_at'], name='uploaded_at_idx'),
        ),
        migrations.AddIndex(
            model_name='skinimageprediction',
            index=models.Index(fields=['predicted_class'], name='predicted_class_idx'),
        ),
    ]
